export const AppString = {
    WelcomeBack: 'Welcome Back',
    LoginToContinue: 'Login to continue',
    EmailAddress: 'Email Address',
    Password: 'Password',
    ForgotPassword: 'Forgot Password ?',
    Login: 'Login',
    Error: 'Error',
    PleaseEnterEmailPsw: 'Please enter email & password',
    InvalidCredentials: 'Invalid Credentials',
    IncorrectEmailPsw: 'Email or password is incorrect',
    QuickActions: 'Quick Actions',
    Attendance: 'Attendance',
    Employees: 'Employees',
    Tasks: 'Tasks',
    FieldVisit: 'Field Visit',
    TodaysActiveEmployees: "Today's Active Employees",
    CheckedInat: 'Checked In',
    CheckedOutAt: 'Checked Out',
    Duration: 'Duration',
    SearchEmployee: 'Search employee...',
    CreateEmployee: 'Create Employee',
    EditEmployee: 'Edit Employee',
    FullName: 'Full Name',
    EnterEmployeeName: 'Enter employee name',
    Email: 'Email',
    EmployeeDetails: "Employee Details",
    NoResultsFound: 'No results found',
    Edit: 'Edit',
    Delete: 'Delete',
    DeleteEmployee: 'Delete Employee',
    ConfirmationDelete: 'Are you sure you want to delete this employee ?',
    EmployeeList: 'Employees',
    SearchFieldVisit: 'Search employee or title...',
    DeleteFieldVisit: 'Delete Field visit',
    ConfirmationDeleteFieldVisit: 'Are you sure you want to delete this field visit ?',
    UpdateEmployee: 'Update Employee',
    TaskLists: 'Tasks',
    PhoneNumber: 'Phone Number',
    TasksSummary: 'Tasks Summary',
    ClockHistory: 'Clock History',
    MyTasks: 'My Daily Tasks',
    EnterPassword: 'Enter password',
    EnterPhoneNumber: 'Enter phone number',
    Designation: 'e.g. Software Engineer',
    ValidationError: 'Validation Error',
    PleaseEnterEmployeeName: 'Please enter employee name...!',
    PleaseEnterEmailAddress: 'Please enter email address...!',
    PleaseEnterPassword: 'Please enter password...!',
    PleaseEnterPhoneNumber: 'Please enter phone number...!',
    PleaseSelectDesignation: 'Please select designation...!',
    PleaseSelectFieldLocation: 'Please select field location...!',
    EGFieldExecutive: 'e.g. Field Executive',
    EnterFieldLocation: 'Enter field location',
    FieldLocation: 'Field Location',
    UpdateTask: 'Update Task',
    CreateTask: 'Create Task',
    PleaseEnterTaskTitle: 'Please enter task title...!',
    PleaseSelectEmployee: 'Please select employee...!',
    PleaseSelectStartDate: 'Please select start date...!',
    PleaseSelectStartTime: 'Please select start time...!',
    SearchTasks: 'Search tasks...',
    EmployeeTasks: 'Employee Tasks',
    DesignationTitle: 'Designation',
    Active: 'Active',
    InActive: 'Inactive',
    Breaks: 'Breaks',
    Total: 'Total:',
    CheckIn: 'Check In',
    CheckOut: 'Check Out',
    Validation: 'Validation',
    CheckInOutRequired: 'Check-in and Check-out are required',
    InvalidTime: 'Invalid Time',
    CheckoutTimeMustAfterCheckin: 'Check-out time must be after Check-in time',
    EditAttendance: 'Edit Attendance',
    Present: 'Present',
    Absent: 'Absent',
    In: 'In',
    Out: 'Out',
    DelBreak: 'Delete Break',
    DelBreakConfirmation: 'Are you sure you want to delete this break?',
    LimitReached: 'Limit reached',
    LimitReachedMsg: 'You can add a maximum of 5 breaks.',
    AddBreak: 'Add Break',
    SaveChanges: "Save Changes",
    InvalidBreak: 'Invalid Break',
    BreakOutMustAfterBreakIn: 'Break out must be after break in',
    Cancel: 'Cancel',
    TaskTitle: 'Task Title',
    TaskDescription: 'Task Description',
    AssignedEmployees: 'Assigned employees',
    Location: 'Location',
    EnterLocationOptional: "Enter location (Optional)",
    SelectStartDateTime: 'Select Start Date & Time',
    SelectEndDateTime: 'Select End Date & Time',
    StartTime: 'Start Time',
    EndDate: 'End Date & Time',
    StartDate: 'Start Date & Time',
    EndTime: 'End Time',
    SelectTaskStatus: 'Select Task Status',
    Logout: 'Logout',
    AreYourSureWantLogout: 'Are you sure you want to logout?',
    Pending: 'Pending',
    NotProvided: 'Not Provided',
    all: 'all',
    TaskDetails: "Task Details",
    Assignment: 'Assignment',
    Employee: "Employee",
    Schedule: 'Schedule',
    WorkLocation: "Work Location",
    Profile: 'Profile',
    MyAttendance: "My Attendance",
    NoAttendanceFoundForThisDate: 'No attendance found for this date',
    TotalWorking: 'Total Hours',
    BreakHours: 'Total Break Hours',
    TotalWorkingHoursDetails: 'Total Hours Details',
    BreakDetails: 'Break Details',
    Dashboard: 'Dashboard',
    Hello: 'Hello',
    InProgress: 'In Progress',
    All: 'All',
    MyTasksEmp: "My Tasks",
    NoTasksAssignedYet: "No Tasks Assigned Yet",
    AssignedToYouAppearHere: "Tasks assigned to you will appear here",
    NotFoundAnyTaskSummary: 'Not found any tasks summary',
    NoTaskFound: 'No tasks found',
    SelectTask: 'Select Task',
    UntitledTask: 'Untitled Task',
    Status: 'Status:',
    SelectATask: 'Select a task',
    PleaseSelectOneTaskToStart: 'Please select one task to start.',
    Start: 'Start',
    HowWouldYouLikeToMark: 'How would you like to mark this task?',
    Completed: 'Completed',
    Description: 'Description',
    TimeLine: 'Timeline',
    End: 'End',
    TimeRemaining: 'Time Remaining',
    AssignedTo: 'Assigned To',
    Close: 'Close',
    SelectAnyOne: "Select Any One",
    FilterTasks: "Filter Tasks",
    DateRange: 'Date Range',
    From: 'From',
    To: 'To',
    Reset: 'Reset',
    Apply: 'Apply',
    DeleteTask: 'Delete Task',
    ConfirmationDeleteTask: 'Are you sure you want to delete this task ?',
    Workingon: 'Working on:-',
    StatusEmpDash: 'Status:-',
    EmployeeTasksHistory: 'Tasks History',
    LoginSuccessfully: "Login Successfully",
    success: "success",
    error: "error",
    EditAttendanceSheet: 'Attendance Updated Successfully',
    EditEmployeeProfile: 'Employee Profile Updated Successfully',
    CreateEmployeeProfile: 'Employee Profile Created Successfully',
    DeleteEmployeeProfile: 'Employee Profile Deleted Successfully',
    TaskUpdatedSuccessfully: 'Task Updated Successfully',
    TaskAddedSuccessfully: 'Task Created Successfully',
    TaskDeletedSuccessfully: 'Task Deleted Successfully',
    LogoutSuccessfully: 'Logout Successfully',
    StartActiveTimeFirst: "Active Time is not started, Please Start active time first",
    YourWorkSessionIsRunning: "Your work session is still active, Please check out first.",
    YourActiveTimeIsRunning: "Your active time is running, Please inActive first.",
    YourBreakInStillRunning: "Your break-in is still running, Please break-out first",
    InvalidEmailAddress: "Invalid email address",
    IncorrectPassword: "Incorrect password",
    InvalidUserRole: "Invalid user role",
    addYourFirstEmployee: "Add your first employee",
    addYourFirstTask: 'Add your first task',
    YouReachedBreakToday: 'You have reached the maximum 5 breaks for today'
}